# Blog settings
# permalink: /blog


# My variables
name: La Frikitiva
description: Diario de un filólogo en Dinamarca.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
